config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations', :passwords => 'users/passwords' }
  scope "/admin" do
    resources :users
  end
  get 'users/me'
  get 'users/me/edit', to: 'users#me_edit'

  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  get "dashboard", to: 'dashboard#index'
  get "room", to: 'welcome#room'

  resources :rooms

  get    'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter
  post   'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter_post
  get    'bbb/room/:id', to: 'bbb#room_status', as: :bbb_room_status
  delete 'bbb/room/:id', to: 'bbb#room_close', as: :bbb_room_close
  get    'bbb/meetings/:id', to: 'bbb#meeting_list'
  get    'bbb/meeting/:id', to: 'bbb#meeting_info'
  delete 'bbb/meeting/:id', to: 'bbb#meeting_end'
  get    'bbb/recordings/:id', to: 'bbb#recording_list'
  patch  'bbb/recording/:room_id', to: 'bbb#recording_publish', as: :bbb_recording_publish
  delete 'bbb/recording/:room_id', to: 'bbb#recording_delete', as: :bbb_recording_delete
  get    'bbb/close'

  get ':landing_id', to: 'welcome#landing'
  get ':landing_id/:room_id', to: 'welcome#room'

  root 'welcome#index'
end

app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base
  has_many :rooms
  has_attached_file :picture, :styles => { :medium => "150x150", :small => "48x48", :icon => "32x32"},
                    :url  => "/assets/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

  include ActionView::Helpers

  ## For paperclip
  #do_not_validate_attachment_file_type :picture
  #validates_attachment_presence :picture
  validates_attachment_size :picture, :less_than => 5.megabytes
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, # :validatable,
         :omniauth_providers => [:twitter, :facebook, :google_oauth2]

  #devise :database_authenticatable, :registerable, :confirmable, :rememberable,
  #              :recoverable, :trackable, :omniauthable, # :validatable,
  #              :authentication_keys => [:subdomain, :login],
  #              :request_keys => [:subdomain],
  #              :reset_password_keys => [:subdomain, :login],
  #              :omniauth_providers => [:digitalocean]
  def self.from_omniauth(auth)
      where(:provider => auth.provider, :uid => auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email || ""
        user.password = Devise.friendly_token[0,20]
        user.username = unique_username(auth.info.email)
      end
  end

  ## Roles implemented using role_model
  # 0000 0001 =  1 = [:admin]
  # 0000 0010 =  2 = [:manager]
  # 0000 0100 =  4 = [:member]
  # 0000 0110 =  6 = [:manager, :member]
  # 0000 0101 =  5 = [:admin, :member]

  # By default, when auto-refistration is allowed all the accounts are created with
  # the role member
  include RoleModel

  # if you want to use a different integer attribute to store the
  # roles in, set it with roles_attribute :my_roles_attribute,
  # :roles_mask is the default name
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :member

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  #def email_required?
  #  super && provider.blank?
  #end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    _login = conditions.delete(:login)
    if _login
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => _login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  def fullname
    _fullname = (self.first_name != nil && self.first_name.strip != '')? self.first_name: ''
    _fullname += (self.last_name != nil && self.last_name.strip != '')? ((_fullname != '')? ' ': '')+self.last_name: ''
    _fullname
  end

  def to_s
    (self.fullname != '')? self.fullname: (self.username != '')? self.username: self.email
  end

  private
  def self.unique_username(email)
    if email != nil
      username = email.split("@").first
    else
      username = random_password(8)
    end
    while User.find_by(:username => username) do
      username = random_password(8)
    end
    username
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def digitalocean
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
  end

  def twitter
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
  end

  def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
  end

  def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  # For devise
  before_filter :authenticate_user!
  # For role_model
  load_and_authorize_resource

  def index
    @user = current_user
    if (@user.has_role? :admin)
      @users = User.all
    else
      @users = User.where(:id => @user.id)
    end
  end

  def new
    # Add the default role
    @user.roles = [:member]
  end

  def create
    # Create a new User based on the parameters received
    @user = User.new(user_params)
    # Add the selected role
    @user.roles = [params[:role]]
    # Save the new User
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    @user = User.find(params[:id])
    @user.roles = [params[:role]]
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def me
    @user = current_user
  end

  def me_edit
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :picture)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def role_name(role_key)
    role_key.capitalize
  end

  def roles
    roles = []
    valid_roles = User.valid_roles
    valid_roles.each do |valid_role|
      role = [role_name(valid_role), valid_role]
      roles << role
    end
    roles
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { :multipart => true, :autocomplete => "off"} do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group input-group col-lg-4 field">
      <%= f.label :username %><br />
      <%= f.text_field :username, autofocus: true, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-4 field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-4 field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-4 field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-4 field">
      <%= f.label :password %><br />
      <% if @user.id == nil %>
      <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Blank if you don't want to set one" %>
      <% else %>
      <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Blank if you don't want to change it" %>
      <% end %>
    </div>

    <!-- <%= @user.role_symbols[0] %> -->
    <div class="form-group input-group col-lg-4 field">
      <%= f.label :role %><br />
      <%= select_tag(:role, options_for_select(roles, @user.role_symbols[0])) %>
    </div>

    <div class="form-group input-group col-lg-4 field">
      <%= f.label :picture %><br />
      <% if @user.picture_file_name.nil? %>
        <div style="width:150px;height:150px;" class="thumbnail">
          <i class="fa fa-user fa-picture"></i>
        </div>
      <% else %>
        <%= image_tag @user.picture.url(:small) %><br /><br />
      <% end %>
      <%= f.file_field :picture %>
    </div>

    <div class="actions">
      <% if @user.id == nil %>
      <%= f.submit "Save", :class => "btn btn-default" %>
      <% else %>
      <%= f.submit "Update", :class => "btn btn-default" %>
      <% end %>
      &nbsp;<%= link_to 'Cancel', url_for(:back), class: "btn btn-default" %>
    </div>

  <fieldset>
<% end %>
<br><br>

app/views/users/_profile.html.erb
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><%= @user.fullname %></h1>
                <% if current_user == @user %>
                <%= link_to '', users_me_edit_path(), id: "profile_edit", :name => "profile_edit", :title => 'Edit', class: "btn btn-default glyphicon glyphicon-edit pull-right" %>
                <% else %>
                <%= link_to '', edit_user_path(@user), id: "profile_edit", :name => "profile_edit", :title => 'Edit', class: "btn btn-default glyphicon glyphicon-edit pull-right" %>
                <% end %>
                <div class="col-sm-6 col-md-3">
                <% if @user.picture_file_name.nil? %>
                  <div style="width:150px;height:150px;" class="thumbnail">
                    <i class="fa fa-user fa-picture"></i>
                  </div>
                <% else %>
                  <%= image_tag @user.picture.url(:small) %>
                <% end %>
                </div>
                <h3>
                  <b>Username:</b> <%= @user.username %><br>
                  <b>Email:</b> <%= @user.email %><br>
                  <b>Roles:</b>
                  <% @user.roles.each do |role| %>
                     <li><%= role_name role %></li>
                  <% end %>
                  <br>
                </h3>
            </div>
        </div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Registered users
          </div>
          <!-- /.panel-heading -->
            <div class="panel-body">
              <%= link_to 'Add user', new_user_path, class: "btn" %>
              <div class="table-responsive table-bordered">
                <table id="users" class="table">
                  <thead>
                    <tr>
                      <th>Username</th>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Email</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @users.each do |user| %>
                    <% if user != current_user %>
                    <tr>
                      <th><%= user.username %></th>
                      <td><%= user.first_name %></td>
                      <td><%= user.last_name %></td>
                      <td><%= user.email %></td>
                      <td>
                        <%= link_to '', user_path(user), :title => 'View', class: "btn btn-default glyphicon glyphicon-file" %>
                        <%= link_to '', edit_user_path(user), :title => 'Edit', class: "btn btn-default glyphicon glyphicon-edit" %>
                        <%= link_to '', user_path(user), :method => :delete, :title => 'Delete', :class => "btn btn-default glyphicon glyphicon-remove", :data => { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                    <% end %>
                  <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>
      <!-- /.col-lg-12 -->

<script>
$(document).ready(function($) {
    $('#users').dataTable ({
        sPaginationType : "full_numbers",
        "columns": [
            null,
            null,
            null,
            null,
           { "width": "114px" }
        ]
    });
});
</script>

app/views/users/me.html.erb
<%= render 'profile' %>

app/views/users/me_edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'profile' %>