config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations', :passwords => 'users/passwords' }
  scope "/admin" do
    resources :users
  end
  get 'users/me'
  get 'users/me/edit', to: 'users#me_edit'

  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  get "dashboard", to: 'dashboard#index'
  get "room", to: 'welcome#room'

  resources :rooms

  get    'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter
  post   'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter_post
  get    'bbb/room/:id', to: 'bbb#room_status', as: :bbb_room_status
  delete 'bbb/room/:id', to: 'bbb#room_close', as: :bbb_room_close
  get    'bbb/meetings/:id', to: 'bbb#meeting_list'
  get    'bbb/meeting/:id', to: 'bbb#meeting_info'
  delete 'bbb/meeting/:id', to: 'bbb#meeting_end'
  get    'bbb/recordings/:id', to: 'bbb#recording_list'
  patch  'bbb/recording/:room_id', to: 'bbb#recording_publish', as: :bbb_recording_publish
  delete 'bbb/recording/:room_id', to: 'bbb#recording_delete', as: :bbb_recording_delete
  get    'bbb/close'

  get ':landing_id', to: 'welcome#landing'
  get ':landing_id/:room_id', to: 'welcome#room'

  root 'welcome#index'
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  validates :name, :presence => true, :length => { :minimum => 5 }

  def owner
     user = User.find_by_id(user_id)
     user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include ApplicationHelper
  include BbbHelper
  #before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @user = current_user
    if (@user.has_role? :admin) || (@user.has_role? :manager)
      @rooms = Room.all
    else
      @rooms = Room.where(:user_id => @user.id)
    end
  end

  def show
    bbb_recordings = bbb_get_recordings @room
    if bbb_recordings[:returncode] && bbb_recordings[:recordings].any?
       @recordings = bbb_recordings[:recordings]
    else
       @recordings = []
    end
  end

  def new
  end

  def create
    @room = Room.new(room_params) do |r|
      r.user_id = current_user.id

      room_params['moderator_password'].strip
      if room_params['moderator_password'].blank?
        r.moderator_password = random_password(8)
      end
      room_params['viewer_password'].strip
      if room_params['viewer_password'].blank?
        begin
          r.viewer_password = random_password(8)
        end while r.moderator_password == r.viewer_password
      end
    end

    if @room.save
      redirect_to @room
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:room][:moderator_password].strip
    if params[:room][:moderator_password].blank?
      params[:room][:moderator_password] = random_password(8)
    end
    params[:room][:viewer_password].strip
    if params[:room][:viewer_password].blank?
      begin
        params[:room][:viewer_password] = random_password(8)
      end while params[:room][:moderator_password] == params[:room][:viewer_password]
    end

    if @room.update(room_params)
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private
    def room_params
        params.require(:room).permit(:name, :description, :welcome, :moderator_password, :viewer_password, :wait_moderator, :recording, :user_id, :permissions)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
  def to_duration(secs)
    ## Display in time duration format 1h25'34"
    h = secs / 3600;      # hours
    m = secs % 3600 / 60; # minutes
    s = secs % 3600 % 60; # seconds
    return "#{format('%02d', h)}:#{format('%02d', m)}:#{format('%02d', s)}"
  end
end

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>

  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited
        this room from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group input-group col-lg-5 field">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-7 field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-7 field">
      <%= f.label :welcome %><br>
      <%= f.text_area :welcome, :class => "form-control" %>
    </div>

    <div class="form-group input-group field">
      <%= f.check_box :wait_moderator %>&nbsp;
      <b>Wait for moderator<b><br>
    </div>

    <div class="form-group input-group field">
      <%= f.check_box :recording %>&nbsp;
      <b>Recording<b><br>
    </div>

    <div class="form-group input-group col-lg-5 field">
      <%= f.label :moderator_password %><br>
      <%= f.text_field :moderator_password, :class => "form-control" %>
    </div>

    <div class="form-group input-group col-lg-5 field">
      <%= f.label :viewer_password %><br>
      <%= f.text_field :viewer_password, :class => "form-control" %>
    </div>

    <div class="action">
      <%= f.submit :class => 'btn btn-primary' %>&nbsp;<%= link_to 'Cancel', url_for(:back), class: "btn btn-default" %>
    </div>

  </fieldset>

<% end %>
<br><br>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Available rooms
          </div>
          <!-- /.panel-heading -->
            <div class="panel-body">
              <%= link_to 'New room', new_room_path, class: "btn" %>
              <div class="table-responsive table-bordered">
                <table id="rooms" class="table">
                  <thead>
                    <tr>
                      <% if @user.has_role? :admin %>
                      <th>Owner</th>
                      <% else %>
                      <th></th>
                      <% end %>
                      <th>Room Name</th>
                      <th>Description</th>
                      <th>Moderator password</th>
                      <th>Viewer password</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @rooms.each do |room| %>
                    <tr>
                      <td>
                      <% if @user.has_role? :admin %>
                        <%= link_to room.owner.to_s, "/"+room.owner.username, :title => 'Show landing page' %>
                      <% end %>
                      </td>
                      <td><%= room.name %></td>
                      <td><%= room.description %></td>
                      <td><%= room.moderator_password %></td>
                      <td><%= room.viewer_password %></td>
                      <td>
                        <%= link_to '', room_path(room), :title => 'View', class: "btn btn-default glyphicon glyphicon-file" %>
                        <%= link_to '', edit_room_path(room), :title => 'Edit', class: "btn btn-default glyphicon glyphicon-edit" %>
                        <% #link_to '', '#', :title => 'Hide', class: "btn btn-default glyphicon glyphicon-eye-open" %>
                        <%= link_to '', room_path(room), :method => :delete, :title => 'Delete', :class => "btn btn-default glyphicon glyphicon-trash", :data => { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>
      <!-- /.col-lg-12 -->

<script>
$(document).ready(function($) {
    $('#rooms').dataTable ({
        sPaginationType : "full_numbers",
        "columns": [
            null,
            null,
            null,
            null,
            null,
           { "width": "114px" }
        ]
    });
});
</script>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
  <% if @room != nil %>
    <% if cannot? :read, @room %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Heads up!</strong> You need to sign in for using this room.
    </div>
    <% else %>
    <div id="room" data-url="<%= bbb_room_status_path(@room) %>" >
      <div id="room_top_bar">
        <%= link_to '', '#', id: "room_refresh", :name => "room_refresh", :title => 'Refresh', class: "btn btn-default glyphicon glyphicon-refresh pull-left" %>
        <%= link_to '', edit_room_path(@room), id: "room_edit", :name => "room_edit", :title => 'Edit', class: "btn btn-default glyphicon glyphicon-edit pull-right" %>
      </div><br>
      <div id="room_info">
        <h1><%= @room[:name] %></h1>
        <h3><%= @room[:description] %></h3>
      </div><br>
      <div id="room_status">
        <div id="room_status_general" class="alert alert-info" role="alert"></div>
        <div id="room_status_current"></div>
      </div><br>
      <div id="room_actionbar">
      <% if can? :use, @room %>
        <span id="room_enter" data-url="<%= bbb_room_enter_path(@room) %>"></span>
      <% end %>
      <% if can? :close, @room %>
        <span id="room_close" data-url="<%= bbb_room_close_path(@room) %>"></span>
      <% end %>
      </div><br>
    </div>
    <% end %>
    <% if @recordings.any? %>
    <div id="div_recordings">
      <h3>Recordings</h3><br>
      <table id="recordings" class="table table-responsive">
        <thead>
          <tr>
            <th>Recording</th>
            <th>Activity</th>
            <th>Description</th>
            <th>Date</th>
            <th>Duration</th>
            <% if can? :manage, @room %>
            <th>Actions</th>
            <% else %>
            <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
        <% @recordings.each do |recording| %>
          <tr id="recording_<%= recording[:recordID] %>">
            <td style="vertical-align: middle !important;">
            <div id="recording_playback_<%= recording[:recordID] %>" class="<% if !recording[:published] %>hide<% end %>">
            <% if recording[:playback][:format].kind_of?(Array) %>
            <% recording[:playback][:format].each do |playback| %>
              <%= link_to playback[:url], id: "recording_"+playback[:type], :name => "recording_"+playback[:type], :title => "Playback "+playback[:type], :target => "_blank", class: "btn btn-default bt-sm" do %>
                  <i class="fa fa-play-circle-o icon-large" aria-hidden="true"></i>
                  <span style="font-size:small;" class="text-capitalize"><%= playback[:type] %></span>
              <% end %>
            <% end %>
            <% else %>
              <%= link_to recording[:playback][:format][:url], id: "recording_"+recording[:playback][:format][:type], :name => "recording_"+recording[:playback][:format][:type], :title => "Playback "+recording[:playback][:format][:type], :target => "_blank", class: "btn btn-default bt-sm" do %>
                  <i class="fa fa-play-circle-o icon-large" aria-hidden="true"></i>
                  <span style="font-size:small;" class="text-capitalize"><%= recording[:playback][:format][:type] %></span>
              <% end %>
            <% end %>
            </div>
            </td>
            <td style="vertical-align: middle !important;"><%= recording[:name] %></td>
            <td style="vertical-align: middle !important;"><%= recording[:metadata][:description]? recording[:metadata][:description]: 'none' %></td>
            <td style="vertical-align: middle !important;"><%= recording[:startTime].in_time_zone %></td>
            <td style="vertical-align: middle !important;"><%= to_duration(recording[:endTime].to_i - recording[:startTime].to_i).to_s %></td>
            <% if can? :manage, @room %>
            <td style="vertical-align: middle !important;">
              <%= image_tag image_path('processing16.gif'), :id => "processing_publish_recording_" + recording[:recordID].to_s, :title => "Processing", :alt => "Processing", :class => "hidden", :style => "float:left;margin:10px;margin-bottom:8px;margin-right:14px" %>
              <span class="recording_action" data-id="<%= recording[:recordID] %>" data-action="<%= recording_status_change(recording) %>" data-url="<%= bbb_recording_publish_path(@room[:id]) %>"></span>
              <%= image_tag image_path('processing16.gif'), :id => "processing_delete_recording_" + recording[:recordID].to_s, :title => "Processing", :alt => "Processing", :class => "hidden", :style => "float:left;margin:10px;margin-bottom:8px" %>
              <span class="recording_action" data-id="<%= recording[:recordID] %>" data-action="delete" data-url="<%= bbb_recording_delete_path(@room[:id]) %>"></span>
            </td>
            <% else %>
            <td></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  <% end %>

<script>
$(document).ready(function($) {

    initButtonRoomRefresh ();
    initButtonRoomEnter ();
    initButtonRoomClose ();
    initRecordingActions ();
    refreshRoom ();
    <% if @recordings.any? %>
    $('#recordings').dataTable ({
        sPaginationType : "full_numbers",
        "columns": [
            null,
            null,
            null,
            null,
            null,
           { "width": "76px" }
        ]
    });
    <% end %>
});
</script>