config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations', :passwords => 'users/passwords' }
  scope "/admin" do
    resources :users
  end
  get 'users/me'
  get 'users/me/edit', to: 'users#me_edit'

  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  get "dashboard", to: 'dashboard#index'
  get "room", to: 'welcome#room'

  resources :rooms

  get    'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter
  post   'bbb/enter/:id', to: 'bbb#enter', as: :bbb_room_enter_post
  get    'bbb/room/:id', to: 'bbb#room_status', as: :bbb_room_status
  delete 'bbb/room/:id', to: 'bbb#room_close', as: :bbb_room_close
  get    'bbb/meetings/:id', to: 'bbb#meeting_list'
  get    'bbb/meeting/:id', to: 'bbb#meeting_info'
  delete 'bbb/meeting/:id', to: 'bbb#meeting_end'
  get    'bbb/recordings/:id', to: 'bbb#recording_list'
  patch  'bbb/recording/:room_id', to: 'bbb#recording_publish', as: :bbb_recording_publish
  delete 'bbb/recording/:room_id', to: 'bbb#recording_delete', as: :bbb_recording_delete
  get    'bbb/close'

  get ':landing_id', to: 'welcome#landing'
  get ':landing_id/:room_id', to: 'welcome#room'

  root 'welcome#index'
end

app/views/layouts/_backend_navigation.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "OpenLand", root_path, :class => "navbar-brand", 'data-no-turbolink' => true %>
      </div>
      <!-- /.navbar-header -->

      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>
            <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li>
              &nbsp;&nbsp;
              <span class="clear">
                <% if current_user.picture_file_name.nil? %>
                <i class="fa fa-user fa-2x"></i>
                <% else %>
                <%= image_tag current_user.picture.url(:icon) %>
                <% end %>
                <strong class="font-bold"><%= current_user.to_s %></strong>
              </span>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "/users/me", method: :get do %>
                <i class="fa fa-user fa-fw"></i> Profile
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, method: :get do %>
                <i class="fa fa-sign-out fa-fw"></i> Sign out
              <% end %>
            </li>
          </ul>
          <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
      </ul>

      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <li>
              <%= link_to dashboard_path, method: :get do %>
                <i class="fa fa-dashboard fa-fw"></i> Dashboard
              <% end %>
            </li>
            <% if current_user.has_role? :admin %>
            <li>
              <%= link_to users_path, method: :get do %>
                <i class="fa fa-users fa-fw"></i> Users
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to rooms_path, method: :get do %>
                <i class="fa fa-table fa-fw"></i> Rooms
              <% end %>
            </li>
          </ul>
        </div>
        <!-- /.sidebar-collapse -->
      </div>
      <!-- /.navbar-static-side -->

    </nav>

app/views/layouts/_head.html.erb
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <title>OpenLand</title>
  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

app/views/layouts/_messages.html.erb
  <div class="container">
    <div class="row">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">x</a>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
      </div>
    <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>
</head>
<body>

  <div id="wrapper">

    <!-- Navigation -->
<%= render 'layouts/backend_navigation' %>

    <div id="page-wrapper">
<%= render 'layouts/messages' %>

      <% if params[:controller] != 'users' || (params[:action] != 'show' && params[:action] != 'me') %>
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header"><%= t('backend.'+params[:controller]) %></h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <% end %>

<%= yield %>

    </div>
    <!-- /#page-wrapper -->


  </div>
  <!-- /#wrapper -->

</body>
</html>

app/views/layouts/bbb.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/classic.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <title>OpenLand</title>
  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

  <!-- Main css styles -->
  <%= stylesheet_link_tag 'classic', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

  <div id="wrapper">
	<%= yield %>
  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>
</head>
<body>

<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/layouts/nova.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>

  <!-- Specific for the module javascript files -->
  <%= javascript_include_tag 'rooms', 'data-turbolinks-track' => true %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/traditional.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <title>OpenLand</title>
  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

  <!-- Main css styles -->
  <%= stylesheet_link_tag 'traditional', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

  <div id="wrapper">
	<%= yield %>
  </div>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>

  <!-- Specific for the module javascript files -->
  <%= javascript_include_tag 'rooms', 'data-turbolinks-track' => true %>
</head>
<body>

<%= yield %>

</body>
</html>